
import com.UserAccounts.Mobilephone;
import com.UserAccounts.ManagerAccount;
import java.util.List;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MALSHANI
 */
public class MobilephoneDetailsDashboard extends javax.swing.JFrame {

    /**
     * Creates new form CashierLogin
     */
    public MobilephoneDetailsDashboard() {
        initComponents();
       
    }
    // link with previous jframe
      public MobilephoneDetailsDashboard(String UserAccountCreatingDashboard) {
        initComponents();
        mobilephonedetails_lbl.setText(UserAccountCreatingDashboard);
    }
      // create search method to search items in mobile phone shop 
      public void search (String search_lbl){
          DefaultTableModel dtm = (DefaultTableModel)updatetable_tbl.getModel();
          TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(dtm); // create object for table row sorter
          updatetable_tbl.setRowSorter(trs);
          trs.setRowFilter(RowFilter.regexFilter(search_lbl));   
      }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        mobilephonedetails_lbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        registerid_lbl = new javax.swing.JLabel();
        phonename_lbl = new javax.swing.JLabel();
        brand_lbl = new javax.swing.JLabel();
        category_lbl = new javax.swing.JLabel();
        price_lbl = new javax.swing.JLabel();
        registerid_txt = new javax.swing.JTextField();
        phonename_txt = new javax.swing.JTextField();
        brand_txt = new javax.swing.JTextField();
        category_txt = new javax.swing.JTextField();
        price_txt = new javax.swing.JTextField();
        add_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        updatetable_tbl = new javax.swing.JTable();
        search_lbl = new javax.swing.JTextField();
        search_txt = new javax.swing.JTextField();
        exit_btn = new javax.swing.JButton();
        view_btn = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("mobile phone dashboard");
        setName("mobile phone dashboard"); // NOI18N

        mobilephonedetails_lbl.setBackground(new java.awt.Color(255, 255, 153));
        mobilephonedetails_lbl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        mobilephonedetails_lbl.setForeground(new java.awt.Color(0, 102, 0));
        mobilephonedetails_lbl.setText("New phone registration");
        mobilephonedetails_lbl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mobilephonedetails_lbl.setName("mobilephonedetails_lbl"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        registerid_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        registerid_lbl.setText("Register ID");
        registerid_lbl.setName("registerid_lbl"); // NOI18N

        phonename_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        phonename_lbl.setText("Phone Name");
        phonename_lbl.setName("phonename_lbl"); // NOI18N

        brand_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        brand_lbl.setText("Brand");
        brand_lbl.setName("brand_lbl"); // NOI18N

        category_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        category_lbl.setText("Category");
        category_lbl.setName("category_lbl"); // NOI18N

        price_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        price_lbl.setText("Price");
        price_lbl.setName("price_lbl"); // NOI18N

        registerid_txt.setName("registerid_txt"); // NOI18N

        phonename_txt.setName("phonename_txt"); // NOI18N

        brand_txt.setName("brand_txt"); // NOI18N

        category_txt.setName("category_txt"); // NOI18N

        price_txt.setName("price_txt"); // NOI18N

        add_btn.setBackground(new java.awt.Color(153, 153, 255));
        add_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add_btn.setText("Add");
        add_btn.setName("add_btn"); // NOI18N
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerid_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phonename_lbl)
                    .addComponent(brand_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(price_lbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(category_lbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(registerid_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(phonename_txt)
                    .addComponent(brand_txt)
                    .addComponent(category_txt)
                    .addComponent(price_txt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(add_btn)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(registerid_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registerid_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phonename_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phonename_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(brand_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(brand_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(category_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(category_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(price_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(price_lbl))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(add_btn)
                        .addContainerGap())))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        updatetable_tbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        updatetable_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "registerid", "phonename ", "brand  ", "category ", "price  "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        updatetable_tbl.setName("updatetable_tbl"); // NOI18N
        jScrollPane2.setViewportView(updatetable_tbl);

        search_lbl.setBackground(new java.awt.Color(255, 255, 204));
        search_lbl.setText("Enter search String :");
        search_lbl.setName("search_lbl"); // NOI18N

        search_txt.setBackground(new java.awt.Color(0, 153, 153));
        search_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        search_txt.setName("search_txt"); // NOI18N
        search_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_txtKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(search_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(search_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        exit_btn.setBackground(new java.awt.Color(255, 153, 51));
        exit_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        exit_btn.setText("Exit");
        exit_btn.setName("exit_btn"); // NOI18N
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });

        view_btn.setBackground(new java.awt.Color(204, 204, 0));
        view_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        view_btn.setText("view");
        view_btn.setName("view_btn"); // NOI18N
        view_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(view_btn)
                            .addComponent(exit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(mobilephonedetails_lbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mobilephonedetails_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(view_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exit_btn))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
            // create add button in mobilephone details dashboard
    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        // TODO add your handling code here:
       Mobilephone md = new Mobilephone() {}; //create object for mobile phone account
       
       int registerid = Integer.parseInt(registerid_txt.getText());
       String phonename  = phonename_txt.getText();
       String brand = brand_txt.getText();
       String category = category_txt.getText();
       int price = Integer.parseInt(price_txt.getText());
        
       md.setRegisterid(registerid);
       md.setPhonename( phonename);
       md.setBrand(brand);
       md.setCategory(category);
       md.setPrice(price);
       
       ManagerAccount mdi = new ManagerAccount(); // create object for manager account
       mdi.Add(md);
      
       registerid_txt.setText("");
       phonename_txt.setText("");
       brand_txt.setText("");
       category_txt.setText("");
       price_txt.setText("");
        
        
    }//GEN-LAST:event_add_btnActionPerformed
            // create exit button
    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit_btnActionPerformed

                  // create view all button
    private void view_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_btnActionPerformed
        // TODO add your handling code here:
        ManagerAccount mdi = new ManagerAccount(); // use above creating object for manager account
        List<Mobilephone> list = mdi.viewAll();
        DefaultTableModel dtm = (DefaultTableModel)updatetable_tbl.getModel(); // create object for default table and it set to get values
        dtm.setRowCount(0);
        for (Mobilephone mp: list){
            
            int registraterid = mp.getRegisterid();
            String phonename  = mp.getPhonename();
            String brand      = mp.getBrand();
            String category   = mp.getCategory();
            int price         = mp.getPrice();
            dtm.addRow(new Object[]{ registraterid,phonename,brand,category,price}); // set view details in jtable
           
        
        }
    }//GEN-LAST:event_view_btnActionPerformed
                // create search text key to search items in jtable
    private void search_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_txtKeyReleased
        // TODO add your handling code here:
        String searchString = search_txt.getText();
        search(searchString);
         
        
    }//GEN-LAST:event_search_txtKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MobilephoneDetailsDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MobilephoneDetailsDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MobilephoneDetailsDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MobilephoneDetailsDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MobilephoneDetailsDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    private javax.swing.JLabel brand_lbl;
    private javax.swing.JTextField brand_txt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel category_lbl;
    private javax.swing.JTextField category_txt;
    private javax.swing.JButton exit_btn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel mobilephonedetails_lbl;
    private javax.swing.JLabel phonename_lbl;
    private javax.swing.JTextField phonename_txt;
    private javax.swing.JLabel price_lbl;
    private javax.swing.JTextField price_txt;
    private javax.swing.JLabel registerid_lbl;
    private javax.swing.JTextField registerid_txt;
    private javax.swing.JTextField search_lbl;
    private javax.swing.JTextField search_txt;
    private javax.swing.JTable updatetable_tbl;
    private javax.swing.JButton view_btn;
    // End of variables declaration//GEN-END:variables
    
}
