/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */



import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author MALSHANI
 */
public class UserAccountCreatingDashboard extends javax.swing.JFrame {
      
    /**
     * Creates new form ManagerLogin
     */
    public UserAccountCreatingDashboard() {
        initComponents();
        
    }
     
         //  link of login page with create new user account
      public UserAccountCreatingDashboard(String createnewuseraccount) {
        initComponents();
        createaccount_lbl.setText(createnewuseraccount);
        
    }
     
       
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createaccount_lbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        firstname_lbl = new javax.swing.JLabel();
        lastname_lbl = new javax.swing.JLabel();
        gender_lbl = new javax.swing.JLabel();
        userid_lbl = new javax.swing.JLabel();
        contactnumber_lbl = new javax.swing.JLabel();
        address_lbl = new javax.swing.JLabel();
        options_lbl = new javax.swing.JLabel();
        firstname_txt = new javax.swing.JTextField();
        lastname_txt = new javax.swing.JTextField();
        userid_txt = new javax.swing.JTextField();
        contactnumber_txt = new javax.swing.JTextField();
        address_txt = new javax.swing.JTextField();
        options_combobox = new javax.swing.JComboBox<>();
        add_btn = new javax.swing.JButton();
        exit_btn = new javax.swing.JButton();
        switch_btn = new javax.swing.JButton();
        gender_combobox = new javax.swing.JComboBox<>();
        username_lbl = new javax.swing.JLabel();
        password_lbl = new javax.swing.JLabel();
        username_txt = new javax.swing.JTextField();
        password_pf = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createaccount_lbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        createaccount_lbl.setForeground(new java.awt.Color(255, 102, 102));
        createaccount_lbl.setText("Create a new user Account");
        createaccount_lbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        createaccount_lbl.setName("createaccount_lbl"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        firstname_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstname_lbl.setText("First Name");
        firstname_lbl.setName("firstname_lbl"); // NOI18N

        lastname_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lastname_lbl.setText("Last Name");
        lastname_lbl.setName("lastname_lbl"); // NOI18N

        gender_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gender_lbl.setText("Gender");
        gender_lbl.setName("gender_lbl"); // NOI18N

        userid_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userid_lbl.setText("User ID");
        userid_lbl.setName("userid_lbl"); // NOI18N

        contactnumber_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        contactnumber_lbl.setText("Contact Number");
        contactnumber_lbl.setName("contactnumber_lbl"); // NOI18N

        address_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        address_lbl.setText("Address");
        address_lbl.setName("address_lbl"); // NOI18N

        options_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        options_lbl.setText("options");
        options_lbl.setName("options_lbl"); // NOI18N

        firstname_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstname_txt.setName("firstname_txt"); // NOI18N

        lastname_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lastname_txt.setName("lastname_txt"); // NOI18N

        userid_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userid_txt.setName("userid_txt"); // NOI18N

        contactnumber_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        contactnumber_txt.setName("contactnumber_txt"); // NOI18N

        address_txt.setName("address_txt"); // NOI18N

        options_combobox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        options_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select user", "Manager", "Cashier" }));
        options_combobox.setName("options_combobox"); // NOI18N

        add_btn.setBackground(new java.awt.Color(0, 102, 102));
        add_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add_btn.setText("ADD");
        add_btn.setName("add_btn"); // NOI18N
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        exit_btn.setBackground(new java.awt.Color(255, 153, 153));
        exit_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        exit_btn.setText("Exit");
        exit_btn.setName("exit_btn"); // NOI18N
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });

        switch_btn.setBackground(new java.awt.Color(255, 255, 102));
        switch_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        switch_btn.setText("SWITCH");
        switch_btn.setName("switch_btn"); // NOI18N
        switch_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switch_btnActionPerformed(evt);
            }
        });

        gender_combobox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gender_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select gender", "Male", "Female" }));
        gender_combobox.setName("gender_combobox"); // NOI18N

        username_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        username_lbl.setText("username");
        username_lbl.setName("username_lbl"); // NOI18N

        password_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        password_lbl.setText("password");
        password_lbl.setName("password_lbl"); // NOI18N

        username_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        username_txt.setName("username_txt"); // NOI18N

        password_pf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        password_pf.setName("password_pf"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(switch_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(add_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exit_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(userid_lbl)
                                            .addComponent(gender_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lastname_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(firstname_lbl))
                                        .addGap(90, 90, 90))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(address_lbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(contactnumber_lbl, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lastname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(firstname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gender_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userid_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contactnumber_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(address_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(options_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(password_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(username_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(options_combobox, 0, 155, Short.MAX_VALUE)
                                    .addComponent(username_txt)
                                    .addComponent(password_pf))))
                        .addContainerGap(37, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstname_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastname_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gender_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gender_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userid_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userid_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactnumber_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactnumber_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(address_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address_lbl))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(options_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(options_lbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username_lbl))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_pf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(add_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exit_btn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(switch_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(createaccount_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(createaccount_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
          //data adding to create new user account
    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        // TODO add your handling code here:
        String firstname = firstname_txt.getText(); 
        String lastname = lastname_txt.getText();
        String gender = gender_combobox.getSelectedItem().toString();
        String userId = userid_txt.getText();
        String contactnumber = contactnumber_txt.getText();
        String address = address_txt.getText();
        String options = options_combobox.getSelectedItem().toString();// user selection for login
        String username = username_txt.getText();
        String password = password_pf.getText();// password show in star mark in cross gettext
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");// provide database connection
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/userlogin","root","");// connect with relevent database 
            Statement stm = con.createStatement(); 
            // insert values to project from the relevent database table
            String sql = "INSERT INTO logindetails VALUES('"+firstname+"','"+lastname+"','"+gender+"','"+userId+"','"+contactnumber+"','"+address+"','"+options+"','"+username+"','"+password+"')";
            stm.executeUpdate(sql); //
            JOptionPane.showMessageDialog(this, "record added"); // after correctly data addimg to table, show massege to out data adding
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(UserAccountCreatingDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_add_btnActionPerformed
            //create exit button
    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
        // TODO add your handling code here:
        System.exit(0); // we use this code to exite in the system
    }//GEN-LAST:event_exit_btnActionPerformed
         //create switch button
    private void switch_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switch_btnActionPerformed
        // TODO add your handling code here:
       //link this jframe with next jframe 
         MobilephoneDetailsDashboard cl = new MobilephoneDetailsDashboard(); //use mobile phone dash boad jframe object
                       cl.setVisible(true); //use to go to next jframe
                       setVisible(false);
    }//GEN-LAST:event_switch_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserAccountCreatingDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserAccountCreatingDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserAccountCreatingDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserAccountCreatingDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserAccountCreatingDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    private javax.swing.JLabel address_lbl;
    private javax.swing.JTextField address_txt;
    private javax.swing.JLabel contactnumber_lbl;
    private javax.swing.JTextField contactnumber_txt;
    private javax.swing.JLabel createaccount_lbl;
    private javax.swing.JButton exit_btn;
    private javax.swing.JLabel firstname_lbl;
    private javax.swing.JTextField firstname_txt;
    private javax.swing.JComboBox<String> gender_combobox;
    private javax.swing.JLabel gender_lbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lastname_lbl;
    private javax.swing.JTextField lastname_txt;
    private javax.swing.JComboBox<String> options_combobox;
    private javax.swing.JLabel options_lbl;
    private javax.swing.JLabel password_lbl;
    private javax.swing.JPasswordField password_pf;
    private javax.swing.JButton switch_btn;
    private javax.swing.JLabel userid_lbl;
    private javax.swing.JTextField userid_txt;
    private javax.swing.JLabel username_lbl;
    private javax.swing.JTextField username_txt;
    // End of variables declaration//GEN-END:variables
}
